name:                projects-hs
version:             0.1.0.0
github:              "ssipos90/projects-hs"
license:             BSD3
author:              "Sebastian Sipos"
maintainer:          "sebastiansipos90@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssipos90/projects-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.6 && < 1.4.7
- bytestring >= 0.10.8.2 && < 0.11
- hedis >= 0.12 && < 0.13
- http-types >= 0.12.3 && < 0.13
- microlens >= 0.4.0 && < 0.5
- microlens-mtl >= 0.1.1 && < 0.2
- microlens-th >= 0.4.2 && < 0.5
- mtl >= 2.2.2 && < 2.3
- protolude >= 0.2 && < 0.3
- scotty >= 0.11.5 && < 0.12
- text >= 1.2.3 && < 1.3

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src

executables:
  projects-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projects-hs

tests:
  projects-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projects-hs
